name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  ci:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Build and Test
        run: |
          dotnet test src/
